name: CinePro
services:
  api:
    build: .
    container_name: CinePro-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
