openapi: 3.0.3
info:
  title: CinePro API
  description: |
    CinePro API provides endpoints to fetch movie and TV show streaming sources from various providers.

    This project is for educational purposes only. We do not host any kind of content. We provide only the links to already available content on the internet. We do not host, upload any videos, films or media files. We are not responsible for the accuracy, compliance, copyright, legality, decency, or any other aspect of the content of other linked sites. If you have any legal issues please contact the appropriate media file owners or host sites.

    You can use this project for personal and NON-COMMERCIAL use ONLY! You are NOT allowed to SELL this project or any part of it and/or ADD ANY KIND of tracking or advertisement to it.
  version: 1.0.0
  license:
    name: Custom License
    url: https://github.com/cinepro-org/backend
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /:
    get:
      summary: API Home
      description: Returns basic information about the API
      operationId: getHome
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  home:
                    type: string
                    example: CinePro API
                  routes:
                    type: object
                    properties:
                      MOVIE:
                        type: string
                        example: /movie/:tmdbID
                      TV:
                        type: string
                        example: /tv/:tmdbID?s=seasonNumber&e=episodeNumber
                  information:
                    type: string
                  license:
                    type: string
                  source:
                    type: string
                    format: url
                    example: https://GitHub.com/cinepro-org/backend
  /movie/{tmdbId}:
    get:
      summary: Get Movie Sources
      description: Returns streaming sources for a movie by TMDB ID
      operationId: getMovieSources
      parameters:
        - name: tmdbId
          in: path
          description: TMDB ID of the movie
          required: true
          schema:
            type: string
            pattern: ^\d+$
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaResponse'
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /movie/:
    get:
      summary: Invalid Movie Request
      description: Returns an error for invalid movie requests
      operationId: getInvalidMovie
      responses:
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tv/{tmdbId}:
    get:
      summary: Get TV Episode Sources
      description: Returns streaming sources for a TV episode by TMDB ID, season, and episode
      operationId: getTvSources
      parameters:
        - name: tmdbId
          in: path
          description: TMDB ID of the TV show
          required: true
          schema:
            type: string
            pattern: ^\d+$
        - name: s
          in: query
          description: Season number
          required: true
          schema:
            type: string
            pattern: ^\d+$
        - name: e
          in: query
          description: Episode number
          required: true
          schema:
            type: string
            pattern: ^\d+$
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaResponse'
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tv/:
    get:
      summary: Invalid TV Request
      description: Returns an error for invalid TV requests
      operationId: getInvalidTv
      responses:
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /{path}:
    get:
      summary: Route Not Found
      description: Returns a 404 error for any undefined routes
      operationId: getRouteNotFound
      parameters:
        - name: path
          in: path
          description: Any undefined path
          required: true
          schema:
            type: string
      responses:
        '404':
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    MediaResponse:
      type: object
      properties:
        files:
          type: array
          description: Array of video files from various sources
          items:
            type: object
            properties:
              file:
                type: string
                description: URL to the video file
                format: uri
              type:
                type: string
                description: Type of the video file
                enum: [hls, mp4, unknown]
              lang:
                type: string
                description: Language of the video
        subtitles:
          type: array
          description: Array of subtitle files
          items:
            type: object
            properties:
              url:
                type: string
                description: URL to the subtitle file
                format: uri
              lang:
                type: string
                description: Language of the subtitle
        errors:
          type: array
          description: Array of errors (only in debug mode)
          items:
            $ref: '#/components/schemas/ErrorObject'
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        response:
          type: integer
          description: HTTP response code
        hint:
          type: string
          description: Hint to help resolve the error
        error:
          type: boolean
          description: Always true for error responses
        reportTo:
          type: string
          description: Link to report the issue (optional)
    ErrorObject:
      type: object
      properties:
        message:
          type: string
          description: Error message
        where did this happen?:
          type: string
          description: Provider where the error occurred
        what could be the cause?:
          type: string
          description: Hint about the possible cause
