blank_issues_enabled: false
contact_links:
  - name: CinePro Issue Tracker
    url: https://github.com/cinepro-org/backend/issues
    about: For technical issues, bugs, and feature requests related to CinePro.