name: Only allow PRs from Dev to Main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dev to Main
        id: pr-check
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          HEAD_REPO="${{ github.event.pull_request.head.repo.full_name }}"
          REPO="${{ github.repository }}"

          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"
          echo "Head repo: $HEAD_REPO"
          echo "Repository: $REPO"

          if [[ "$BASE_BRANCH" != "main" || "$HEAD_BRANCH" != "dev" || "$HEAD_REPO" != "$REPO" ]]; then
            echo "result=fail" >> $GITHUB_OUTPUT
          else
            echo "result=pass" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if check fails
        if: steps.pr-check.outputs.result == 'fail'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "❌ Only PRs from 'dev' to 'main' in the same repository are allowed. This PR will be closed."
            })

      - name: Close PR if check fails
        if: steps.pr-check.outputs.result == 'fail'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            })

      - name: Fail workflow if check fails
        if: steps.pr-check.outputs.result == 'fail'
        run: exit 1

      - name: Success message if check passes
        if: steps.pr-check.outputs.result == 'pass'
        run: echo "✅ Pull request is valid (Dev → Main)."
