name: Only allow PRs from Dev to Main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dev to Main
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          
          if [[ "${{ github.event.pull_request.base.ref }}" != "main" || \
                "${{ github.event.pull_request.head.ref }}" != "dev" || \
                "${{ github.event.pull_request.head.repo.full_name }}" != "cinepro-org/backend" ]]; then
            echo "Invalid PR source or destination. Posting comment and closing PR."

            curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"body": "Only Pull Requests from [dev](https://github.com/cinepro-org/backend/tree/dev) are allowed to be merged to [main](https://github.com/cinepro-org/backend/tree/main). This PR will be closed. Please merge into dev first. ❌"}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

            curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"state": "closed"}' \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{
